jdbc.driver=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
jdbc.url=jdbc:log4jdbc:mariadb://192.168.0.66:3306/picenter
jdbc.username=root
jdbc.password=cyEkR2V/Q2oN1jQH62MiX2xlTJWxEUpR
db.backup.path=/home/picenter/backup/db/
