jdbc.driver=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
jdbc.url=jdbc:log4jdbc:mariadb://192.168.0.66:3306/rmpicenter?useCursorFetch=true&useCompression=true
jdbc.username=root
#jdbc.password=vmfpsxmfl123
# sonar-project.properties 
jdbc.password=ENC(H/FK3rBcQc3Jg1slgquphw==)
# SELECT TO_BASE64(AES_ENCRYPT('vmfpsxmfl123', 'PICenterTree0119'));