#recon.count=4
recon.count=1
recon.api.version=beta

recon.url=https://192.168.0.68:8339
recon.id=admin
recon.password=x2LXslmmmCr99nbqoUDSaycS52vKjsuU

recon.url_2=https://192.168.0.69:8339
recon.id_2=admin
recon.password_2=fHJWErJsDAyRQmj5QpY+Q1zjNGdBMq1B

recon.url_3=https://192.168.0.229:8339
recon.id_3=admin
recon.password_3=fHJWErJsDAyRQmj5QpY+Q1zjNGdBMq1B

recon.url_4=https://192.168.0.160:8339
recon.id_4=admin
recon.password_4=fHJWErJsDAyRQmj5QpY+Q1zjNGdBMq1B

pic_version=picenter
recon.license = 1000

user.key=PICenterTree119@
#pic.main.jsp=main_lotte
pic.main.jsp=main
send.host=smtp.worksmobile.com
send.port=465
picenter.ssl.enable = true
picenter.auth = true

excel.save.path=D:/python/summary.bat
config.excel.time=14

pic.mysql.dump=/home/picenter/mariadb/bin/mysqldump

pic.md5=
pic.sha1=
pic.sha256=
pic.filename=/home/picenter/Tomcat/webapps/ROOT.war

recon.md5=e0dc976296339f5d611a39620afc2383
recon.sha1=2909d0b099a88dcab0db24360eb4fad749454833
recon.sha256=3b6ba23deaff8282d3c152b042733d71ccfb168321ec8346e30602956a99b31b
recon.filename=/home/picenter/Tomcat/webapps/ROOT.war
recon.version=0.0

recon.AppConfig = ""
excel.count=0
excel.url=http://192.168.0.16:8080
excel.url2=http://192.168.0.68

# LG생활건강 OTP Configuration
otp.lgotp.test.mode=true
otp.lgotp.test.code=123456
otp.lgotp.server.ip=10.40.122.158
otp.lgotp.server.port=1812
otp.lgotp.shared.secret=picenter123
otp.lgotp.retry.cnt=1
otp.lgotp.timeout=30
otp.lgotp.nasid=null

