#recon.count=4
recon.count=3
recon.api.version=beta

recon.url=https://192.168.0.68:8339
recon.id=admin
recon.password=fren1212

recon.url_2=https://192.168.0.69:8339
recon.id_2=admin
recon.password_2=fren1212

recon.url_3=https://192.168.0.206:8339
recon.id_3=admin
recon.password_3=fren1212

recon.AppConfig = ""
recon.license = 1000