
recon.count=1
recon.api.version=v1

pic_version=rm_2.0
company_pwd=vmfpsxmfl123!

# LDAP Configuration
ldapUrl=ldap://localhost:389

recon.url=https://192.168.0.68:8339
recon.id=admin
# sonar-project.properties 
recon.password=M9hYw4+7x1IPgxOHAsbAwQ==

recon.url_2=https://192.168.0.69:8339
recon.id_2=admin
# sonar-project.properties 
recon.password_2=M9hYw4+7x1IPgxOHAsbAwQ==

recon.AppConfig = ""

recon.license = 1000
pattern.count = 8
pic.pass.key=PICenterTree0119

saveAttchPath=C:/Temp/attach/
nhemailpath=e:/Temp/email/
